### ISSUE TITLE
Upgraded package

### ISSUE THREAD

**Issue by yasminrajabi** [puppetlabs/puppetlabs-package#22]
Not sure if it's too late for this, it's more of a "nice to have". When I choose the package action=upgrade but the version of that package is already up to date the output just shows me the version, it doesn't tell me if something was changed or not. If we had a way of notifying users whether the package was upgraded or not (changed=true/false) it would be helpful.

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.\n\nWe're going to close it but please do raise another issue if the issue still persists. 😄
