### ISSUE TITLE
Puppet-Agent is required on target nodes

### ISSUE THREAD

**Issue by glennsarti** [puppetlabs/puppetlabs-package#58]
Due to https://github.com/puppetlabs/puppetlabs-package/blob/master/tasks/init.rb#L2 puppet-agent, or at least an instance of ruby with the puppet gem are required on the target node.

However this is left out of the documentation i.e.

https://github.com/puppetlabs/puppetlabs-package/commit/ce63f0eb67dafea9c2f144ea78a9e74a3c96b3af

should read

`.. Machines receiving task requests must have SSH or WinRM services enabled and have a ruby installation with the puppet gem available` or similar.

**Comment by MikaelSmith** [comment]
I'm trying to address this with https://github.com/puppetlabs/puppetlabs-package/pull/96.

**Comment by tphoney** [comment]
this is resolved.
